controllers/MarafonController.php
<?php

namespace app\controllers;

use app\components\MyResizer;
use app\helpers\My;
use app\models\Calories;
use app\models\Care;
use app\models\CoupleMembers;
use app\models\CoupleVote;
use app\models\DetoxDay;
use app\models\ExpressExercise;
use app\models\Faq;
use app\models\GroupMember;
use app\models\LoginForm;
use app\models\Markers;
use app\models\Popups;
use app\models\Potato;
use app\models\Progress;
use app\models\Questions;
use app\models\RationComplex;
use app\models\Recipe;
use app\models\Recommendation;
use app\models\Ref;
use app\models\Report;
use app\models\ReportHasUser;
use app\models\Retail;
use app\models\User;
use app\models\Vote;
use app\models\VoteInstruction;
use app\models\VoteNew;
use app\models\WeekProducts;
use app\services\payment\PaymentFactory;
use gietos\yii\Dadata\Client;
use Hashids\Hashids;
use http\Url;
use RetailCrm\ApiClient;
use RetailCrm\Exception\CurlException;
use yii\base\Exception;
use yii\base\Security;
use yii\data\Pagination;
use yii\db\ActiveQuery;
use yii\db\Expression;
use yii\helpers\ArrayHelper;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\VarDumper;
use yii\imagine\Image;
use yii\web\Controller;
use yii\web\Response;
use yii\web\UploadedFile;

class MarafonController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        /** @var $user User */
        $this->layout = 'marafon';
        $this->enableCsrfValidation = false;
        if (
            Yii::$app->getUser()->getIsGuest()
            && $action->id != 'signup'
            && $action->id != 'payment'
            && $action->id != 'continue'
            && $action->id != 'remember'
        ) {
            if (!isset($_GET['shortID'])) {
                return $this->redirect('/')->send();
            }
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     * @throws \Throwable
     */
    public function actionIndex()
    {
        /**
         * @var $user User
         */


        if (Yii::$app->getUser()->getIsGuest()) {
            return $this->redirect('/');
        }
        if (isset($_GET['avatar'])) {
            Yii::$app->session->set('avatar', $_GET['avatar']);
            Yii::$app->session->set('url', Yii::$app->request->referrer);
            return $this->redirect('/');
        }
        $user = Yii::$app->getUser()->getIdentity();

        $every_day = My::getEveryDayTask();
        return $this->render('index', ['every_day' => $every_day, 'user' => $user]);
    }

    public function actionInstruction()
    {
        /** @var User $user */
        if (Yii::$app->getUser()->getIsGuest()) {
            return $this->redirect(['/']);
        }
        $user = Yii::$app->getUser()->getIdentity();

        $cur_day = $user->groupMember->getCurrentDay();
        $week = $user->groupMember->getCurrentWeek();
        $instruction = My::getEveryDayTask();
        return $this->render('instruction', [
            'instruction' => $instruction,
            'cur_week' => $week,
            'cur_day' => $cur_day,
            'member' => $user->groupMember,
        ]);
    }


    public function actionFood($week = null, $number = null)
    {
        /** @var User $user */
        $user = Yii::$app->getUser()->identity;
        $select_week = Yii::$app->request->getQueryParam('week', 1);
        $select_number = Yii::$app->request->getQueryParam('number', 1);
        $cur_day = $user->groupMember->getCurrentDay();
        $rationsCustom = $user->groupMember->getRationComplex($select_week, $select_number);
        foreach ($rationsCustom as $ration) {
            $ration->calculateCalories($user->groupMember);
        }

        if ($user->groupMember->minMaxWeekDay($select_week, $select_number)) {
            return $this->redirect(Yii::$app->request->referrer);
        }
        return $this->render('food/food', [
            'rationsCustom' => $rationsCustom,
            'cur_week' => $user->groupMember->getCurrentWeek(),
            'select_week' => $select_week,
            'select_number' => $select_number,
            'member' => $user->groupMember,
            'cur_day' => $cur_day,
        ]);
    }

    /**
     * @param int $week
     * @return string
     */
    public function actionProducts($week = 1)
    {
        /** @var User $user */
        /** @var WeekProducts [] $ration */
        $user = Yii::$app->user->identity;
        $ration = WeekProducts::find()->getContent()->where(['week' => $week, 'veg' => $user->groupMember->veg])->one();
        $select_week = Yii::$app->request->getQueryParam('week', $week);
        if ($user->groupMember->minMaxWeekDay($select_week, 1)) {
            return $this->redirect(Yii::$app->request->referrer);
        }

        return $this->render('food/products', [
            'product' => $ration,
            'member' => $user->groupMember,
            'cur_week' => $user->groupMember->getCurrentWeek(),
            'select_week' => $select_week,
        ]);

    }

    public function actionCalories($cat_id = null, $more = 20)
    {
        /** @var User $user */

        $calories = Calories::find()->getContent();
        if ($cat_id) {
            $calories->where(['cat_id' => $cat_id]);
        }
        $user = Yii::$app->user->identity;
        $calories = $calories->orderBy('cat_id ASC')->all();
        return $this->render('food/calories', ['calories' => $calories, 'cur_type' => $cat_id, 'member' => $user->groupMember]);
    }

    public function actionPotato()
    {
        /** @var User $user */

        $models = Potato::find()->getContent()->all();
        $user = Yii::$app->user->identity;
        return $this->render('food/potato', ['models' => $models, 'member' => $user->groupMember]);
    }

    public function actionDetoxDay()
    {
        /** @var User $user */
        $user = Yii::$app->user->identity;
        $detox = DetoxDay::find()->limit(1)->getContent()->orderBy('id  DESC')->all();
        $member = $user->groupMember;
        return $this->render('food/detox', ['detox' => $detox, 'member' => $member]);
    }

    public function actionRecipes()
    {
        /**
         * @var $user User
         */
        $user = Yii::$app->user->identity;
        $type = Yii::$app->request->getQueryParam('type', null);
        $recipes = Recipe::find()->getContent()->where(($type !== null) ? ['type' => $type] : []);
        $countRecipes = clone $recipes;
        $pages = new Pagination([
            'totalCount' => $countRecipes->count(),
        ]);
        $models = $recipes->offset($pages->offset)
            ->all();
        $types_if = ArrayHelper::index(Recipe::find()->getContent()->all(), 'id', ['type']);
        return $this->render('food/recipes', [
            'types' => Recipe::getTypes(),
            'types_if' => $types_if,
            'cur_type' => $type,
            'cur_week' => $user->groupMember->getCurrentWeek(),
            'recipes' => $models,
            'pages' => $pages,
            'member' => $user->groupMember,
        ]);
    }

    public function actionRecipe()
    {
        $recipe_id = Yii::$app->request->getQueryParam('recipe', 1);
        $recipe = Recipe::find()->getContent()->where(['recipe.id' => $recipe_id])->one();
        return $this->renderPartial('food/recipes_ajax', [
            'recipe' => $recipe,
        ]);
    }

    public function actionVoteImg($member_id)
    {
        $member = GroupMember::findOne($member_id);
        return $this->renderPartial('vote_ajax', [
            'member' => $member,
        ]);
    }


    protected function calculateCalories($rations)
    {
        /** @var User $user */
        /** @var $rations RationComplex[] */

        $user = Yii::$app->getUser()->identity;

        foreach ($rations as $ration) {
            $ration->calculateCalories($user->groupMember);
        }

    }

    public function actionFaq($type)
    {
        /** @var User $user */
        $items = [];
        $faqs = Faq::find()->getContent()->where(['type' => $type])->orderBy('id DESC')->all();
        foreach ($faqs as $faq) {
            $items[] = [
                'header' => $faq->title,
                'content' => $faq->content,
            ];
        }
        $user = Yii::$app->getUser()->identity;
        return $this->render('faq', [
            'member' => $user->groupMember,
            'title' => Faq::getFaqType()[$type],
            'items' => $items,
            'type' => $type
        ]);
    }

    public function actionTrainings()
    {
        /** @var User $user */
        /** @var GroupMember $member */
        $user = Yii::$app->getUser()->identity;
        $select_week = Yii::$app->request->getQueryParam('week', 1);
        $select_number = Yii::$app->request->getQueryParam('number', 1);
        $training_type = Yii::$app->request->getQueryParam('training', $user->groupMember->training_type);
        /** @var GroupMember $member */
        if ($user->groupMember->minMaxWeekDay($select_week, $select_number)) {
            return $this->redirect('trainings');
        }

        $exercises = $user->groupMember->getExercises($select_week, $select_number);
        return $this->render('training/trainings', [
            'exercises' => $exercises,
            'cur_week' => $user->groupMember->getCurrentWeek(),
            'select_week' => $select_week,
            'select_number' => $select_number,
            'member' => $user->groupMember,

views/marafon/bonus.php
<?php

/* @var $this yii\web\View */

/* @var $user \app\models\User */
/* @var $referrals \app\models\Ref[] */

/* @var $userRef \app\models\User */

use yii\helpers\Url;

$this->title = 'Бонусы';
$url = str_replace('lk.', '', Yii::$app->request->hostInfo);
?>
<div class="referralProgram">
    <h1>Реферальная программа</h1>

    <div class="referralProgram-introtext">
        Ваша ссылка для рекомендации (отправьте ее тем, кто интересуется марафоном):
    </div>

    <div class="referralProgramForm">
        <input type="text" class="referralProgramForm-input"
               value="https://lerchek.ru?ref=<?= base64_encode($user->email) ?>">
        <button class="referralProgramForm-btn" onclick="copytext('.referralProgramForm-input')">Cкопировать ссылку
        </button>
    </div>

    <div class="referralProgramForm-pol">
        Копируя и передавая ссылку, вы соглашаетесь с условиями <a href="#" class="training_access access_popup ref">агентского
            договора-оферты</a>
    </div>
    <div class="referralProgramConclusion">
        <div class="referralProgramConclusion-name">
            Вывести средства на телефон
        </div>
        <?php
        ?>
        <div class="referralProgramConclusion-box">
            <?php $form = \yii\widgets\ActiveForm::begin([
                'options' => [
                    'class' => 'referralProgramConclusion-grid'
                ]

            ]); ?>

            <?= $form->field($model, 'phone')->widget(\yii\widgets\MaskedInput::className(), [
                'mask' => '8 (999) 999-99-99',
                'options' => [
                    'required' => 'required',
                    'class' => 'referralProgramConclusion-phone',
                    'id' => 'phone2',
                    'placeholder' => ('Телефон')
                ],

            ])->label(false) ?>


            <?= $form->field($model, 'sum')->textInput(['class' => 'referralProgramConclusion-sum', 'placeholder' => 'Сумма', 'required' => 'required', 'min' => 1000])->label(false) ?>
            <?php
            if ($result) {
                ?>
                <div class="referralProgramConclusion-consideration">
                    <span>в обработке</span>
                    <i></i>
                </div>
                <?php
            } else {
                ?>
                <?= \yii\helpers\Html::submitButton('Вывести', ['class' => 'referralProgramConclusion-btn', 'disabled' => $all_sum >= 1000 ? null : 'disabled']) ?>
                <?php
            }
            \yii\widgets\ActiveForm::end(); ?>


            <div class="referralProgramConclusion-ball">
                <div class="referralProgramConclusion-ball__item">
                    На счету: <strong><?= $all_sum ? $all_sum : 0 ?> </strong>р.
                </div>

                <div class="referralProgramConclusion-ball__item">
                    Вывод средств доступен от <strong>1000</strong> р.
                </div>

            </div>
            <div class="referralProgramConclusion-ball">
                <div class="referralProgramConclusion-ball__item custom">
                    Внимание: Выводить средства можно только на российский номер телефона
                </div>
            </div>

        </div>
    </div>


    <div class="referralProgramHistory">
        <div class="referralProgramHistory-name">
            История транзакций:
        </div>

        <table>
            <thead>
            <tr>
                <th width="200">
                    Дата
                </th>
                <th>
                    Программа/номер телефона
                </th>
                <th width="200">
                    Сумма
                </th>
                <th width="120">
                    Статус
                </th>
            </tr>
            </thead>

            <tbody>
            <?php
            foreach ($referrals as $referral) {
                ?>
                <tr>
                    <td>
                        <?= date('d.m.Y', strtotime($referral->date)) ?>
                    </td>
                    <td>
                        <?= stristr($referral->sum, '+') ? \app\helpers\My::$type_program_rus[$referral->member->type_program] : $referral->phone ?>
                    </td>
                    <td>
                        <?= $referral->sum ?>
                    </td>
                    <td>
                        <?= \app\models\Ref::$statuses[$referral->status] ?>
                    </td>
                </tr>

                <?php
            }
            ?>
            </tbody>
        </table>
    </div>

</div>
<?= Yii::$app->controller->renderPartial('../../popups/ref') ?>

views/marafon/calendar.php
<?php
/**
 * @var $this \yii\web\View
 * @var $view integer
 * @var $user \app\models\User
 * @var $markers array
 */
$this->registerJs('
document["markers"] = ' . new \yii\web\JsExpression(\yii\helpers\Json::encode($markers)) . ';
document["markers_group"] = ' . new \yii\web\JsExpression(\yii\helpers\Json::encode(\yii\helpers\ArrayHelper::index($markers, 'id', 'second_date'))) . ';
', \yii\web\View::POS_HEAD);
\app\helpers\My::getAccess();
?>
    <input type="hidden" class="user_id" value="<?= $user->id ?>">
    <div class="diary">
        <h3 class="diary__title" style="text-align: center; margin-bottom: 20px;">Календарь активности</h3>
        <div class="calendar">
            <div class="calendar__prev"></div>
            <div class="calendar__current"></div>
            <div class="calendar__next"></div>
            <div><span class="btn">Отметьте как прошел день</span>
            </div>
            <div class="hint hint_message">
                <div class="hint__close"></div>
                <div class="hint__title">Подсказка</div>
                <div class="hint__text">кликните на число, чтобы отметить, что вы делали в этот день</div>
            </div>
        </div>
        <div class="calendar-wrapper">
            <div id="calendar"></div>
            <div class="hint hint--day">
                <div class="hint__close"></div>
                <div class="hint__title"></div>
                <div class="hint__text">Как прошел ваш день?</div>
                <div class="hint__body">
                    <div class="hint__row hint__row--power"><span class="hint__btn" data-type="power">Добавить</span>
                        <img class="hint__ico" src="../images/calendar/event_power.png" alt=""><span
                                class="hint__training">Тренировка</span>
                    </div>
                    <div class="hint__row hint__row--cardio"><span class="hint__btn" data-type="cardio">Добавить</span>
                        <img class="hint__ico" src="../images/calendar/event_cardio.png" alt=""><span
                                class="hint__training">Кардио</span>
                    </div>
                    <div class="hint__row hint__row--food"><span class="hint__btn" data-type="food">Добавить</span>
                        <img class="hint__ico" src="../images/calendar/event_food.png" alt=""><span
                                class="hint__training">Нарушение</span>
                    </div>
                    <div class="hint__row hint__row--ill"><span class="hint__btn" data-type="ill">Добавить</span>
                        <img class="hint__ico" src="../images/calendar/event_ill.png" alt=""><span
                                class="hint__training">Плохое самочувствие</span>
                    </div>
                    <?php
                    if (\app\helpers\My::isGirl()) {
                        ?>
                        <div class="hint__row hint__row--care"><span class="hint__btn" data-type="care">Добавить</span>
                            <img class="hint__ico" src="../images/calendar/event_cream.png" alt=""><span
                                    class="hint__training">Уход</span>
                        </div>
                        <div class="hint__row hint__row--blood"><span class="hint__btn"
                                                                      data-type="blood">Добавить</span>
                            <img class="hint__ico" src="../images/calendar/event_blood.png" alt=""><span
                                    class="hint__training">Критические дни</span>
                        </div>
                        <?php
                    }
                    ?>
                </div>
            </div>
            <div class="clearfix">
                <div class="calendar-wrapper__left"><a class="btn btn--addtoday js-calendar-addtoday"
                                                       href="#">Добавить</a>
                </div>
            </div>
        </div>
    </div>
<?= $this->render('../../popups/calendar') ?>

views/marafon/change-password.php
<?php

/* @var $this yii\web\View */

/* @var $success bool */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Смена пароля';
$active_menu = 'change_password';
?>
<h1>Смена пароля</h1>
<div class="profile_changepassword">
    <?php

    $form = ActiveForm::begin([
        'fieldConfig' => [
            'options' => ['class' => 'form_group clearfix'],
            'template' => "{label}\n<div class=\"col_right\">{input}\n<div class=\"error\">{error}</div></div>",
        ],
    ]) ?>
    <?= $form->field($user, 'orig_password')->passwordInput()->label('Старый пароль') ?>
    <?= $form->field($user, 'new_password')->passwordInput()->label('Новый пароль') ?>
    <?= $form->field($user, 'password1')->passwordInput()->label('Повтор пароля') ?>
    <?php
    if ($success) {
        echo '<div style="color: red;margin-bottom: 10px;">Пароль успешно изменен</div>';
    }
    ?>
    <?= Html::submitButton('Сменить пароль', ['class' => 'button button_green button_big']) ?>
    <?php ActiveForm::end(); ?>
</div>

views/marafon/change-program.php
<?php
/**
 * @var $member \app\models\GroupMember
 * @var $user \app\models\User
 */
$this->title = 'Выбор программы';
$user = Yii::$app->user->identity;
?>
    <h1><?= $this->title ?></h1>
<?php
foreach (Yii::$app->session->getAllFlashes() as $key => $flash) {
    echo '<div class="alert-' . $key . '>">' . $flash . '</div>';
}
if (count($user->groupMembers) > 1) {
    ?>
    <div class="program-list">
        <?php
        foreach (array_reverse($user->groupMembers) as $member) {
            ?>
            <a href="<?= \yii\helpers\Url::to(['change-program', 'type' => $member->type_program]) ?>"
               class="program-list__link">
                <img src="/images/marathon/program<?= $member->type_program ?>.png?v=1.0" alt="">
                <?php
                if ($member->group_id && date('Y-m-d H:i:s') >= $member->group->datetime_start) {
                    ?>
                    <span class="program-list__link-txt program-list__link-txt--<?= $member->type_program ?>"><?= implode('<br>(', explode('(', \app\helpers\My::$type_program_rus[$member->type_program])) ?></span>
                    <?php
                } else {
                    ?>
                    <span class="program-list__link-txt program-list__link-txt--<?= $member->type_program ?>">
                        <p style="font-weight: bold">(Ожидайте старта)</p>
                        <?= implode('<br>(', explode('(', \app\helpers\My::$type_program_rus[$member->type_program])) ?>
                    </span>
                    <?php
                }
                ?>
                <span class="program-list__link-hover program-list__link-hover--<?= $member->type_program ?>">Перейти</span>
            </a>
            <?php
        }
        ?>
    </div>
    <?php
}

views/marafon/error.php
<?php
/**
 * @var $members array
 * @var $user \app\models\User
 */
$this->title = 'Ошибка';
$user = Yii::$app->user->identity;
?>
<h1><?= $this->title ?></h1>

<div class="program-list">
    <a href="<?= \yii\helpers\Url::to('/') ?>"
       class="program-list__link">
        Что-то пошло не так...
        Нажмите на кнопку ниже, чтобы вернуться на "главную страницу"
        <br>
        <span>Главная</span>
    </a>
</div>

views/marafon/profile.php
<?php

/* @var $this yii\web\View */

/* @var $user \app\models\User */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Профиль';
?>
<h1>Профиль</h1>
<div class="profile_changepassword">
    <div class="profile_photo custom_photo">
        <div class="col-md-1"></div>
        <?php
        $form = ActiveForm::begin([
            'fieldConfig' => [
                'options' => ['class' => 'form_group clearfix'],
                'template' => "{label}\n<div class=\"col_right\">{input}\n<div class=\"help-block\">{error}</div></div>",
            ],
        ]) ?>
        <?= $form->field($user, 'email')->textInput(['disabled' => true]) ?>
        <?= $form->field($user->groupMember, 'last_name') ?>
        <?= $form->field($user->groupMember, 'first_name') ?>
        <?= $form->field($user->groupMember, 'patronymic') ?>
        <?= $form->field($user->groupMember, 'phone') ?>
        <?= $form->field($user->groupMember, 'height') ?>
        <?= $form->field($user->groupMember, 'weight') ?>
        <?= $form->field($user->groupMember, 'bust') ?>
        <?= $form->field($user->groupMember, 'waist') ?>
        <?= $form->field($user->groupMember, 'hip') ?>
        <?= $form->field($user->groupMember, 'city')->textInput() ?>
        <?php
        if (\app\helpers\My::isGirl()) {
            echo $form->field($user->groupMember, 'family')->radioList([
                1 => 'Замужем',
                2 => 'Не замужем',
            ]);
        } else {
            echo $form->field($user->groupMember, 'family')->radioList([
                1 => 'Женат',
                2 => 'Не женат',
            ]);
        }
        ?>
        <?= $form->field($user->groupMember, 'childs', [
            'template' => "<div class='left_col'>{label}\n<div class='hint'>если у вас нет детей, поставьте в этом пункте - 0</div></div><div class=\"col_right\">{input}\n<div class=\"error\">{error}</div></div>",
        ])->textInput(['autocomplete' => 'off']) ?>
        <?= $form->field($user->groupMember, 'telegram')->textInput(['autocomplete' => 'off']) ?>
        <?= $form->field($user->groupMember, 'vk_nick', [
            'template' => "<div class='left_col'>{label}\n<div class='hint'>если у вас нет профиля в инстаграм, напишите – нет</div></div><div class=\"col_right\">{input}\n<div class=\"error\">{error}</div></div>",
        ])->textInput(['autocomplete' => 'off']) ?>
        <?= $form->field($user->groupMember, 'parthner', [
            'template' => "<div class='left_col'>{label}\n<div class='hint'>если вы участвуете самостоятельно, напишите в поле ниже – нет</div></div><div class=\"col_right\">{input}\n<div class=\"error\">{error}</div></div>",
        ])->textInput(['autocomplete' => 'off']) ?>
        <?= $form->field($user->groupMember, 'physical_activity')->radioList(\app\helpers\My::isGirl() ? \app\models\forms\SignupForm::$physical_activities : \app\models\forms\SignupForm::$physical_activities_man, ['class' => 'physical_activity'])->label('Дневная активность ' . Html::img('/images/project/help-button.png', ['class' => 'help_img'])) ?>


        <?= $form->field($user->groupMember, 'training_type')->radioList(\app\models\Training::getTrainingType()) ?>
        <?= $form->field($user->groupMember, 'veg')->radioList($user->groupMember->getVeg()) ?>
        <?= $form->field($user->groupMember, 'ration_type')->radioList($user->groupMember->getTypes()) ?>

        <?= $form->field($user->groupMember, 'smoke')->radioList([
            1 => 'Да',
            2 => 'Нет',
        ]) ?>
        <?= $form->field($user->groupMember, 'alcohol')->radioList(\app\models\GroupMember::getAlcoholType()) ?>
        <?php
        if (\app\helpers\My::isGirl()) {
            ?>
            <?= $form->field($user->groupMember, 'gv_info')->radioList(\app\models\GroupMember::getGV()) ?>
            <?= $form->field($user->groupMember, 'pregnant')->radioList(\app\models\GroupMember::getPregnantType()) ?>
            <?php
        }
        ?>
        <?= $form->field($user->groupMember, 'food_last_3days')->label('Какие цели ставите на ближайшие 4 недели?') ?>

        <?= Html::submitButton('Сохранить', ['class' => 'button button_green button_big']) ?>

        <?php ActiveForm::end(); ?>
    </div>
</div>
<style>
    input {
        -webkit-appearance: checkbox;
    }

    .radio input {
        display: inline !important;
    }

    #groupmember-veg {
        text-align: start;
    }

    #groupmember-ration_type {
        text-align: start;
    }

    #groupmember-smoke, #groupmember-alcohol, #groupmember-gv_info, #groupmember-pregnant {
        text-align: start;
    }

    @media (max-width: 1024px) {
        .profile_changepassword form input {
            height: auto;
        }

        .profile_changepassword {
            padding: 4.6875vw 8.59375vw 0vw;
        }

        .button {
            margin-top: 5vw;
        }
    }
</style>

views/marafon/vote-instruction-new.php
<?php
?>
<div class="food_list">
    <div class="food_item">
        <div class="food_item_name">
            <?= $inst[0]->text ?>
        </div>
    </div>
</div>

<div style="text-align: center;margin-top: 5%">
    <div>
        <input type="checkbox" class="custom-checkbox" id="happy" name="happy" value="yes">
        <label for="happy">Согласен с условиями голосования</label>
    </div>
    <button class="button button_green agree_button" href="/marafon/voting" disabled="disabled">Начать</button>
</div>

views/marafon/vote.php
<?php
/**
 * @var $img []|string
 * @var $cur_type integer
 * @var $calories \app\models\Calories[]
 * @var $member \app\models\GroupMember
 * @var $user \app\models\User
 */

use \yii\helpers\Url;

$user = Yii::$app->user->identity;
//\app\helpers\My::getAccess();
?>
<h1>Выбор участников</h1>
<div class="food_menu_list">
    <div class="food_menu__list">
        <div class="food_menu_item <?= ($cat === null) ? 'active' : '' ?>"><a
                    href="<?= Url::to(['marafon/vote']) ?>" class="button button_transparent">Голосование</a></div>

        <div class="food_menu_item <?= $cat == 1 ? 'active' : null ?>"><a
                    href="<?= Url::to(['marafon/vote', 'cat' => 1]) ?>"
                    class="button button_transparent <?= $cat == 1 ? 'active' : null ?>">Инструкция</a>
        </div>
    </div>
</div>
<?php
if ($cat) {
    ?>
    <p style="margin-bottom: 25px">
        <?= Yii::$app->controller->renderPartial('vote-instruction') ?>
    </p>
    <?php
}
?>

<div class="food_list clearfix vote-list">
    <?php
    if (!empty($members) && !$cat) {
        shuffle($members);
        foreach ($members as $member) {
            ?>
            <div class="vote-item">
                <div> Голосов:
                    <span class="count-vote"><?= \app\models\Vote::find()->where(['vote_id' => $member->id])->count() ?></span>
                </div>

                <a href="<?= Url::to(['marafon/vote-img', 'member_id' => $member->id]) ?>" class="recipes_popup_opener">
                    <div class="food_list_item">
                        <img src="/uploads/progress/<?= $member->avatar ?>" alt="">
                    </div>
                </a>
                <?php
                if ((\app\models\Vote::findOne(['vote_id' => $member->id, 'member_id' => Yii::$app->user->identity->groupMember->id])) === null) {
                    ?>
                    <button class="send-vote"
                            data-member="<?= $member->id ?>">Проголосовать
                    </button>
                    <?php
                } else {

                    ?>
                    <button class="vote-success js-remove-vote"
                            data-member="<?= $member->id ?>">Удалить голос
                    </button>
                    <?php
                }
                ?>
            </div>
            <?php
        }
        ?>

        <?= \yii\widgets\LinkPager::widget([
            'pagination' => $pages,
        ]); ?>
        <?php
    }
    ?>

    <?= Yii::$app->controller->renderPartial('../../popups/vote-json') ?>
    <?= Yii::$app->controller->renderPartial('../../popups/vote-block', ['member' => $user->groupMember]) ?>
</div>