modules/admin/controllers/UserController.php
<?php

namespace app\modules\admin\controllers;

use app\helpers\My;
use app\models\Calories;
use app\models\CoupleMembers;
use app\models\forms\UserView;
use app\models\GroupMember;
use app\models\PaymentLer;
use app\models\Popups;
use app\models\Recipe;
use Yii;
use app\models\User;
use app\models\search\UserSearch;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends MyController
{

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = GroupMember::find()->where(['id' => $id])->one();
        $model->visible_curator = in_array(Yii::$app->user->identity->email, My::$curators_high) ? 2 : 1;
        $popup = Popups::find()->where(['member_id' => $id, 'popup_id' => 2])->one();
        if ($popup === null) {
            $popup = new Popups();
        }
        if (isset($_POST['no_error'])) {
            $popup->description = '<strong>Ваши фото отсмотрены куратором, замечаний у него нет.
                    Но последняя ответственность все равно за вами лично! Куратор лишь дает свои рекомендации. </strong><br>
                    Все инструкции, как правильно сделать фото и видео, выложены в телеграмм канале и в инструкциях в разделе прогресс. 
                    В случае, если куратор не обнаружил какую-то ошибку, ответственность за правильность фото и надписи все равно лежит на вас!';
            $popup->popup_id = 2;
            $popup->status = 0;
            $popup->member_id = $id;
            $popup->curator_id = Yii::$app->user->id;
            $popup->save(false);
        }
        if (isset($_POST['yes_error'])) {
            $popup->description = $_POST['Popups']['description'];
            $popup->popup_id = 2;
            $popup->status = 0;
            $popup->member_id = $id;
            $popup->curator_id = Yii::$app->user->id;
            $popup->save(false);
        }
        if ($this->saveFile($model) && $model->save() && Yii::$app->request->isPost) {
            Yii::$app->session->setFlash('success', 'Успешно!');
        }

        return $this->render('view', [
            'model' => $model,
            'popup' => $popup,
        ]);
    }

    public function actionDisable($id)
    {
        $model = GroupMember::find()->where(['id' => $id])->one();
        $model->visible_curator = false;
        $model->save(false);
        Yii::$app->session->setFlash('success', 'Успешно!');
        return $this->redirect(Yii::$app->request->referrer);
    }


    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (
            $model->load(Yii::$app->request->post()) && $model->save(false)
            && $model->groupMember->load(Yii::$app->request->post()) && $model->groupMember->save(false)
            && $model->groupMember->payment->load(Yii::$app->request->post()) && $model->groupMember->payment->save(false)
        ) {
            Yii::$app->session->setFlash('success', 'Успешно!');
            return $this->redirect(['index']);
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if ($model->groupMember->payment) {
            $model->groupMember->payment->delete();
        }
        $model->groupMember->delete();
        if (empty($model->groupMembers)) {
            $model->delete();
        }
        Yii::$app->session->setFlash('success', 'Успешно удален!');
        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

    public function actionPaymentAdmin()
    {
        /**
         * @var $user User
         */
        $this->enableCsrfValidation = false;
        $post = Yii::$app->request->post();
        $user = User::find()->where(['email' => $post['email']])->one();
        if (!$user) {
            $user = new User();
        }
        $user->setAttributesAdmin();
        if ($user->save(false)) {
            $member = $user->groupMember;
            if ($member === null) {
                $member = new GroupMember();
            }
            $member->setAttributesAdmin($user->id);
            if ($member->save(false)) {
                $pay = $user->groupMember->payment;
                if ($pay === null) {
                    $pay = new PaymentLer();
                }
                $pay->setAttributesAdmin($member->id);
                if ($pay->save(false)) {
                    My::sendEmail($member, 'generate-link-' . My::$type_program[$user->session_type], Yii::$app->params['generate-link-' . My::$type_program[$user->session_type]]);
                    Yii::$app->session->setFlash('success', 'Успешно! ' . $user->email . ' создан!');
                    return false;
                }
            }
        }
        Yii::$app->session->setFlash('error', 'Ошибка попробуйте еще раз!');
        return $this->redirect(['index']);
    }

    public function actionContinue($id)
    {
        $user = User::findOne($id);
        if ($user->groupMember->payment->doplata) {
            $user->groupMember->payment->doplata = false;
            Yii::$app->session->setFlash('success', 'Успешно! ' . $user->email . ' Программа 1.0 вкл!');
        } else {
            $user->groupMember->payment->doplata = true;
            $user->groupMember->payment->date_payment = date('Y-m-d H:i:s');
            Yii::$app->session->setFlash('success', 'Успешно! ' . $user->email . ' Программа 2.0 вкл!');
        }
        $user->groupMember->payment->save(false);
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionChangeProgram($type_program)
    {
        $user = User::findOne(Yii::$app->getUser()->getId());
        $user->session_type = $type_program;
        $user->save(false);
        Yii::$app->session->setFlash('success', 'Успешно! Вы в программе ' . My::$type_program_rus[$user->session_type]);
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionSetRating()
    {
        $user = User::findOne(['email' => $_POST['email']]);
        if ($user) {
            if ($_POST['rating'] == 3) {
                \app\models\Vote::deleteAll(['vote_id' => $user->groupMember->id]);
            }
            $user->groupMember->rating = $_POST['rating'];
            $user->groupMember->save(false);
        }
    }

    public function actionRemoveRating()
    {
        $user = User::findOne(['email' => $_POST['email']]);
        if ($user) {
            $user->groupMember->rating = null;
            $user->groupMember->save(false);
        }
    }

    public function actionDeleteImage($id)
    {
        $model = GroupMember::findOne($id);
        $dir = Yii::getAlias('@webroot/uploads/progress/');
        unlink($dir . $model->avatar);
        $model->avatar = null;
        return json_encode($model->save(false));
    }

    public function saveFile($model)
    {
        $dir = Yii::getAlias('@webroot/uploads/progress/');
        if (!file_exists($dir)) {
            mkdir($dir, 0777, true);
        }
        $file = UploadedFile::getInstance($model, 'img');
        if (!empty($file)) {
            if ($model->avatar) {
                unlink($dir . $model->avatar);
            }
            $fname = uniqid("", true) . '.' . $file->extension;
            $model->avatar = $fname;
            return $file->saveAs($dir . $fname);
        }
        return true;
    }

    public function actionCreateCouple($group_id)
    {
        /**
         * @var $members GroupMember[]
         */
        $couples = [];
        $members = GroupMember::find()->where(['group_id' => $group_id])->andWhere(['rating' => My::CONCURS])->all();
        CoupleMembers::deleteAll(['group_id' => $group_id]);
        $new_arr_group = [];
        foreach ($members as $key => $member) {
            if ($member->vote_category) {
                $new_arr_group[$member->vote_category][] = $member->id;
            }
        }
        foreach ($new_arr_group as $group => $members) {
            foreach ($members as $key => $member) {
                $numb = $key / 2;
                if (is_int($numb)) {
                    $couples[$group . $key] = $member;
                }
                if (is_float($numb)) {
                    $couples[$group . ($key - 1)] .= '.' . $member;
                }
            }
        }

modules/admin/views/group/_form.php
<?php

use yii\helpers\Html;
use \kartik\form\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Group */
/* @var $form \kartik\form\ActiveForm */
?>

<div class="group-form">

    <?php
    $form = ActiveForm::begin([
        'id' => 'login-form-horisonal',
        'type' => ActiveForm::TYPE_VERTICAL,
        'options' => ['enctype' => 'multipart/form-data']
    ]);
    ?>
    <div class="col-row">
        <div class="col-md-6">
            <?= $form->field($model, 'num')->textInput(['maxlength' => true]) ?>

            <?php
            echo '<label>Дата старта 1.0</label>';
            echo \kartik\date\DatePicker::widget([
                'model' => $model,
                'attribute' => 'datetime_start',
                'options' => ['placeholder' => 'Выбрать дату старта'],
                //  'convertFormat' => true,
                'pluginOptions' => [
                    'todayHighlight' => true,
                    'autoclose' => true,
                    'format' => 'yyyy-mm-dd',
                ]
            ]);
            ?>
            <?= $form->field($model, 'link_main')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-6">
            <?php
            echo '<label>Дата окончания потока</label>';
            echo \kartik\date\DatePicker::widget([
                'model' => $model,
                'attribute' => 'date_continue',
                'options' => ['placeholder' => 'Выбрать дату окончания потока'],
                //  'convertFormat' => true,
                'pluginOptions' => [
                    'todayHighlight' => true,
                    'autoclose' => true,
                    'format' => 'yyyy-mm-dd',
                ]
            ]);
            ?>
            <?= $form->field($model, 'link_second')->textInput(['maxlength' => true]) ?>
            <?php
            if ($model->isNewRecord) {
                ?>
                <?= $form->field($model, 'is_clone')->checkbox() ?>
                <?php
            }
            ?>
            <div class="form-group">
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
            </div>

        </div>
    </div>


    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/group/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\GroupSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="group-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'num') ?>

    <?= $form->field($model, 'datetime_create') ?>

    <?= $form->field($model, 'datetime_start') ?>

    <?= $form->field($model, 'datetime_end') ?>

    <?php // echo $form->field($model, 'state') ?>

    <?php // echo $form->field($model, 'training_type') ?>

    <?php // echo $form->field($model, 'date_continue') ?>

    <?php // echo $form->field($model, 'instruction_main') ?>

    <?php // echo $form->field($model, 'instruction_second') ?>

    <?php // echo $form->field($model, 'link_main') ?>

    <?php // echo $form->field($model, 'link_second') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/group/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Group */

$this->title = "Создание группы";
$this->params['breadcrumbs'][] = ['label' => 'Группы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="group-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/group/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\GroupSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Группы, всего клиентов: ' . $count;
$this->params['breadcrumbs'][] = $this->title;
?>
<ul>
    <li>
        Дорогой куратор, здесь будет краткий manual по работе фильтров.
    </li>
    <li>
        1)<strong>"нажми на иконку "глазик" что бы перейти в просмотр списка клиентов группы"</strong>
    </li>
    <li>
        2)<strong>"Начало"</strong> фильтр клиентов, которые загрузили или отредактировали фото "Начало", к этому
        фильтру доступны в связке любые другие фильтры ниже из списка(не голубые кнопки)
    </li>
    <li>
        3)<strong>"Коллаж"</strong> фильтр клиентов, которые загрузили или отредактировали фото на
        4ой неделе программы + начало + есть коллаж + ссылка на видео
    </li>
    <li>
        4)<strong>"Все"</strong> Выводит всех клиентов
    </li>
    <li>
        5)<strong>"Для удобства используйте разные фильтры в связках"</strong>
    </li>
    <li>
        6)<strong style="color:red;">"Если хочешь посмотреть новых клиетов, которые исправили фото, просто надо выбрать
            в фильтре "Статус сообшения" -> "Исправлено(ждёт ответа)" и доп фильтр (Начало)"</strong>
    </li>
    <li>
        7)<strong>"Email"</strong> Этот фильтр ищет всех клиентов данного потока !!! Не работает в связке с другими
        фильтрами
    </li>
</ul>
<div class="group-index">
    <?= \kartik\grid\GridView::widget([
        'id' => 'kv-grid-demo',
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'num',
            [
                'attribute' => '',
                'label' => 'Участники',
                'value' => function (\app\models\Group $model) {
                    return $model->membersCount;
                }
            ],
            'datetime_create',
            'datetime_start',
            'date_continue',
            'link_main',
            'link_second',
            [
                'class' => 'yii\grid\ActionColumn',
                'visibleButtons' =>
                    [
                        'delete' => Yii::$app->user->identity->email == 'admin@lerchek.ru' ? true : false,
                        'change' => Yii::$app->user->identity->email == 'admin@lerchek.ru' ? true : false,
                        'update' => Yii::$app->user->identity->role == \app\models\User::ROLE_ADMIN && Yii::$app->user->identity->email == 'admin@lerchek.ru' ? true : false
                    ],

                'template' => '<span style="text-wrap: none">{view} {update} {delete} {change}</span>',
                'header' => 'Действия',
                'buttons' => [
                    'update' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil custom"></span>', \yii\helpers\Url::to(['update', 'id' => $model->id]), [
                            'title' => 'Редактировать'
                        ]);

                    },
                    'view' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', \yii\helpers\Url::to(['view-users', 'id' => $model->id]), [
                            'title' => 'Редактировать'
                        ]);

                    },

                    'change' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-time"></span>', \yii\helpers\Url::to(['change-group', 'id' => $model->id]), [
                            'title' => 'Перенос'
                        ]);
                    },

                ]
            ]
            ,
        ], // check the configuration for grid columns by clicking button above
        'containerOptions' => ['style' => 'overflow: auto'], // only set when $responsive = false
        'headerRowOptions' => ['class' => 'kartik-sheet-style'],
        'filterRowOptions' => ['class' => 'kartik-sheet-style'],
        'pjax' => true, // pjax is set to always true for this demo
        // set your toolbar
        'toolbar' => [
            [
                'content' => '<a href="' . \yii\helpers\Url::to(['create']) . '" class="btn btn-default" title="Создать новую группу">Создать новую группу</a>',
                'options' => ['class' => 'btn-group mr-2']
            ],
            [
                'content' => in_array(Yii::$app->user->identity->email, \app\helpers\My::$curators_high) ? '<a href="' . \yii\helpers\Url::to(['delete-group-completed']) . '" class="btn btn-info">Удалить сообщения</a>' : null,
                'options' => ['class' => 'btn-group mr-2', 'id' => 'pModal']
            ],
            [
                'content' => in_array(Yii::$app->user->identity->email, \app\helpers\My::$curators_high) ? '<a href="' . \yii\helpers\Url::to(['delete-group-visible']) . '" class="btn btn-info">Снять метки</a>' : null,
                'options' => ['class' => 'btn-group mr-2', 'id' => 'pModal']
            ],

            '{export}',
        ],
        'toggleDataContainer' => ['class' => 'btn-group mr-2'],
        // set export properties
        'export' => [
            'fontAwesome' => true
        ],
        // parameters from the demo form
        'bordered' => true,
        'striped' => true,
        'condensed' => true,
        'responsive' => true,
        'hover' => true,
        'showPageSummary' => false,
        'panel' => [
            'type' => \kartik\grid\GridView::TYPE_PRIMARY,
            'heading' => 'Группы',
            'before' => '',
            'after' => false,
            'showFooter' => false
        ],
        'persistResize' => false,
        'toggleDataOptions' => ['minCount' => 1],
        'itemLabelSingle' => 'Группа',
        'itemLabelPlural' => 'Группы'
    ]) ?>
</div>

modules/admin/views/group/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Group */

$this->title = 'Редактирование: ' . $model->num;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Groups'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="group-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/group/user-group.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\User */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $group  \app\models\Group */

$this->title = 'Клиенты группы: ' . $group->num;
$this->params['breadcrumbs'][] = $this->title;
?>
<ul>
    <li>
        Дорогой куратор, здесь будет краткий manual по работе фильтров.
    </li>
    <li>
        1)<strong>"Начало"</strong> фильтр клиентов, которые загрузили или отредактировали фото "Начало", к этому
        фильтру доступны в связке любые другие фильтры ниже из списка(не голубые кнопки)
    </li>
    <li>
        2)<strong>"Коллаж"</strong> фильтр клиентов, которые загрузили или отредактировали фото на
        4ой неделе программы + начало + есть коллаж + ссылка на видео
    </li>
    <li>
        3)<strong>"Все"</strong> Выводит всех клиентов
    </li>
    <li>
        4)<strong>"Для удобства используйте разные фильтры в связках"</strong>
    </li>
    <li>
        5)<strong style="color:red;">"Если хочешь посмотреть новых клиетов, которые исправили фото, просто надо выбрать
            в фильтре "Статус сообшения" -> "Исправлено(ждёт ответа)" и доп фильтр (Начало)"</strong>
    </li>
    <li>
        6)<strong>"Email"</strong> Этот фильтр ищет всех клиентов данного потока !!! Не работает в связке с другими
        фильтрами
    </li>

</ul>

<?php

?>
<div class="user-index">

    <?= \kartik\grid\GridView::widget([
        'id' => 'kv-grid-demo',
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'email',
                'format' => 'raw',
                'value' => function (\app\models\User $model) {
                    $css = 'black';
                    if (!$model->groupMember->payment) {
                        $css = 'red';
                    }
                    return '<div style="color: ' . $css . '">' . $model->groupMember->user->email . '</div>';
                },
                'filterInputOptions' => [
                    'class' => 'form-control',
                    'placeholder' => 'Email'
                ],

            ],
            [
                'attribute' => '',
                'label' => 'password',
                'value' => function (\app\models\User $model) {
                    return in_array(Yii::$app->user->identity->email, \app\helpers\My::$curators_password) ? $model->groupMember->password : 'Доступно старшему куратору';
                }
            ],
            [
                'attribute' => 'read',
                'label' => 'Статус сообщения',
                'value' => function (\app\models\User $model) {
                    if ($model->groupMember->progressPopup) {
                        return \app\models\Popups::$statuses[$model->groupMember->progressPopup->status];
                    } else {
                        return 'Нет сообщений';
                    }
                },
                'filter' => \app\models\Popups::$statuses + ['4' => 'Нет сообщений']
            ],
            [
                'attribute' => 'visible_curator',
                'label' => 'Статус осмотра',
                'format' => 'raw',
                'value' => function (\app\models\User $model) {
                    if ($model->groupMember->visible_curator == 1) {
                        return '<span style="background-color: red;color:white">Младший куратор</span>';
                    } elseif ($model->groupMember->visible_curator == 2) {
                        return '<span style="background-color: green;color:white">Старший куратор</span>';
                    }
                    return '<span style="background-color: #3c8dbc;color:white">Не просмотрено</span>';
                },
                'filter' => \app\models\User::$visible_curators
            ],
            [
                'label' => 'Дата загрузки фото',
                'format' => 'raw',
                'value' => function (\app\models\User $model) {
                    if ($model->groupMember->progressRelLastWeek) {
                        return $model->groupMember->progressRelLastWeek->date_create;
                    }
                    if ($model->groupMember->progressRelFirstWeek) {
                        return $model->groupMember->progressRelFirstWeek->date_create;
                    }
                    return 'Фото не загружено';
                },
                'filter' => \app\models\User::$visible_curators
            ],
            [
                'attribute' => 'rating',
                'label' => 'Оценка куратора',
                'value' => function (\app\models\User $model) {
                    return \app\helpers\My::$type_voices[$model->groupMember->rating];
                },
                'filter' => \app\helpers\My::$type_voices + [4 => 4, 5 => 5]
            ],
            [
                'attribute' => '',
                'label' => 'Кто дал ответ на фото',
                'value' => function (\app\models\User $model) {
                    return $model->groupMember->progressPopup->curator->email;
                },
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'visibleButtons' =>
                    [
                        'view' => true,
                        'avatar' => Yii::$app->user->identity->role == \app\models\User::ROLE_ADMIN ? true : false
                    ],

                'template' => '<span style="text-wrap: none">{view} {disable} {avatar}</span>',
                'header' => 'Действия',
                'buttons' => [
                    'view' => function ($url, \app\models\User $model) {
                        if ($model->groupMember->visible_curator == 2) {
                            return Html::a('<span style="color: green" class="glyphicon glyphicon-eye-open"></span>', \yii\helpers\Url::to(['/admin/user/view', 'id' => $model->groupMember->id]), [
                                'title' => 'Редактировать'
                            ]);
                        }
                        return Html::a('<span style="color: ' . ($model->groupMember->visible_curator ? "red" : "#3c8dbc") . '" class="glyphicon glyphicon-eye-open"></span>', \yii\helpers\Url::to(['/admin/user/view', 'id' => $model->groupMember->id]), [
                            'title' => 'Редактировать'
                        ]);

                    },
                    'disable' => function ($url, \app\models\User $model) {
                        return Html::a('<span class="glyphicon glyphicon-retweet"></span>', \yii\helpers\Url::to(['/admin/user/disable', 'id' => $model->groupMember->id]), [
                            'title' => 'Снять красный глаз'
                        ]);

                    },
                    'avatar' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-user"></span>', \yii\helpers\Url::to(['/marafon/index', 'avatar' => $model->id]), [
                            'title' => 'Аватар',
                            'data' => [
                                'confirm' => 'Переключить на Аватар?',
                                'method' => 'post',
                            ],
                        ]);

                    },


                ]
            ]
            ,
        ], // check the configuration for grid columns by clicking button above
        'containerOptions' => ['style' => 'overflow: auto'], // only set when $responsive = false
        'headerRowOptions' => ['class' => 'kartik-sheet-style'],
        'filterRowOptions' => ['class' => 'kartik-sheet-style'],
        'pjax' => true, // pjax is set to always true for this demo
        // set your toolbar
        'toolbar' => [
            [
                'content' => '<a href="' . \yii\helpers\Url::to(['view-users', 'id' => $_GET['id'], 'progress-first' => 1]) . '" class="btn btn-info">Начало</a>',
                'options' => ['class' => 'btn-group mr-2', 'id' => 'pModal']
            ],

            [
                'content' => '<a href="' . \yii\helpers\Url::to(['view-users', 'id' => $_GET['id'], 'progress-completed' => 1]) . '" class="btn btn-info">Коллаж</a>',
                'options' => ['class' => 'btn-group mr-2', 'id' => 'pModal']
            ],
            [
                'content' => '<a href="' . \yii\helpers\Url::to(['view-users', 'id' => $_GET['id']]) . '" class="btn btn-info">Все</a>',
                'options' => ['class' => 'btn-group mr-2', 'id' => 'pModal']
            ],
            [
                'content' => in_array(Yii::$app->user->identity->email, \app\helpers\My::$curators_high) ? '<a href="' . \yii\helpers\Url::to(['delete-group-completed', 'id' => $_GET['id']]) . '" class="btn btn-info">Удалить сообщения</a>' : null,
                'options' => ['class' => 'btn-group mr-2', 'id' => 'pModal']
            ],
            [
                'content' => in_array(Yii::$app->user->identity->email, \app\helpers\My::$curators_high) ? '<a href="' . \yii\helpers\Url::to(['delete-group-visible', 'id' => $_GET['id']]) . '" class="btn btn-info">Снять метки</a>' : null,
                'options' => ['class' => 'btn-group mr-2', 'id' => 'pModal']
            ],
            [
                'content' => in_array(Yii::$app->user->identity->email, \app\helpers\My::$curators_high) ? '<a href="' . \yii\helpers\Url::to(['user/create-couple', 'group_id' => $_GET['id']]) . '" class="btn btn-info">Сформировать пары</a>' : null,
                'options' => ['class' => 'btn-group mr-2', 'id' => 'pModal']
            ],

        ],

        'toggleDataContainer' => ['class' => 'btn-group mr-2'],
        // set export properties
        'export' => [
            'fontAwesome' => true
        ],
        // parameters from the demo form
        'bordered' => true,
        'striped' => true,
        'pjaxSettings' => [
            'options' => [
                'timeout' => '50000'
            ]
        ],
        'condensed' => true,
        'responsive' => true,
        'hover' => true,
        'showPageSummary' => false,
        'panel' => [
            'type' => \kartik\grid\GridView::TYPE_PRIMARY,
            'heading' => 'Список участников: ' . $group->num,
            'before' => '',
            'after' => false,
            'showFooter' => false
        ],
        'persistResize' => false,
        'toggleDataOptions' => ['minCount' => 1],
        'itemLabelSingle' => 'Клиент',
        'itemLabelPlural' => 'Клиентов'
    ]) ?>
</div>